DefaultContentLanguage = "en"
baseURL = "/"
googleAnalytics = "UA-66152192-3"
[languages]
  [languages.en]
    title = "#SaveTheData"
    weight = 1
  [languages.es]
    title = "#SaveTheData"
    weight = 2